image:
  repository: jacobamar1/flaskdemo
  tag: "latest"

service:
  type: ClusterIP
  port: 5000

ingress:
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  host: test.10.0.0.6.nip.io
  path: /